name: flutter_network_watcher_example
description: Example app demonstrating the flutter_network_watcher package
version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_network_watcher:
    path: ../

publish_to: none

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
