name: flutter_network_watcher
description: Real-time network connectivity monitoring with offline queue management for Flutter applications.
version: 0.0.3
homepage: https://pub.dev/packages/flutter_network_watcher
repository: https://github.com/Dhia-Bechattaoui/flutter_network_watcher
issue_tracker: https://github.com/Dhia-Bechattaoui/flutter_network_watcher/issues
documentation: https://pub.dev/documentation/flutter_network_watcher

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.0.0
  rxdart: ^0.28.0
  shared_preferences: ^2.0.0
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  flutter_lints: ^6.0.0
  mockito: ^5.0.0

flutter:
  # This package is a plugin
  plugin:
    platforms:
      android:
        package: com.example.flutter_network_watcher
        pluginClass: FlutterNetworkWatcherPlugin
      ios:
        pluginClass: FlutterNetworkWatcherPlugin
      web:
        pluginClass: FlutterNetworkWatcherPlugin
        fileName: flutter_network_watcher_web.dart
      windows:
        pluginClass: FlutterNetworkWatcherPluginCApi
      linux:
        pluginClass: FlutterNetworkWatcherPlugin
      macos:
        pluginClass: FlutterNetworkWatcherPlugin

topics:
  - networking
  - connectivity
  - offline
  - queue
  - monitoring
